using Xunit;

namespace Pcg.Oracle.Tests;

/// <summary>
/// Oracle tests that compare Pcg64 output against the C++ reference implementation
/// using JSON test vectors generated by the C++ oracle tool.
/// </summary>
public class Pcg64OracleTests
{
    public static IEnumerable<object[]> GetTestCases() => OracleDataLoader.Load("pcg64");

    [Theory]
    [MemberData(nameof(GetTestCases))]
    public void Pcg64_MatchesOracle_Json(OracleTestCase testCase)
    {
        ulong seedHi = testCase.SeedHi != null ? ulong.Parse(testCase.SeedHi) : 0UL;
        ulong seedLo = testCase.SeedLo != null ? ulong.Parse(testCase.SeedLo) : 0UL;
        ulong streamHi = testCase.StreamHi != null ? ulong.Parse(testCase.StreamHi) : 0UL;
        ulong streamLo = testCase.StreamLo != null ? ulong.Parse(testCase.StreamLo) : 0UL;

        var seed = new UInt128(seedHi, seedLo);
        var stream = new UInt128(streamHi, streamLo);

        var rng = new Pcg64(seed, stream);

        foreach (var entry in testCase.Sequence)
        {
            ulong actual = rng.Next();
            ulong expected = entry.AsUInt64();
            Assert.Equal(expected, actual);
        }
    }
}
